language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

install:
  - npm install

jobs:
  include:
    - stage: lint
      name: "Lint"
      script: npm run lint
    - stage: test
      name: "Test"
      script: npm run test
