query  getContributor($login: String!){ 
  organization{
    totalIssues
    totalPullRequests
    totalCommits
    contributor(login: $login){
      id
      login
      name
      location
      bio
      email
      websiteUrl
      avatarUrl
      firstContributionDate
      totalCommits
      totalIssues
      totalPullRequests
      totalIssuesOpen
      totalIssuesClosed
      totalPullRequestsOpen
      totalPullRequestsClosed
    }
  }
}