query contributors($quantity: Int!){ 
  organization {
    contributors(first: $quantity) {
      login
      name
      avatarUrl
      bio
      websiteUrl
      totalIssues
      totalCommits
      totalPullRequests
    }
  }
}