query repositories($quantity: Int!) { 
  organization {
    repositories(maxNumberOfRepositories: $quantity) {
      id
      name
      totalOpenIssues
      totalOpenPullRequests
      totalStars
      totalForks
    }
  }
}